language: php
php:
- 5.6
- 7.0
- 7.1
- 7.2
- hhvm

matrix:
  allow_failures:
  - php: hhvm

cache:
  directories:
  - ~/.composer/cache/files

before_install:
- phpenv config-rm xdebug.ini || true

install:
- composer update --optimize-autoloader --prefer-dist

script:
- composer validate --strict
- vendor/bin/behat --strict -vvv --no-interaction